Mobile version setup contact form
sharon-odhiambo/My-Portfolio-Site pull request #3
Opened 2022-06-08 21:19 UTC by sharon-odhiambo

Add contact-form website dynamics
Add form validations
Style contact form using css
Fix stylelint errors

2022-06-08 21:55 UTC, zieeco requested changes
Hi @sharon-odhiambo  and @Hirwacardinalloic 


Great work with the contact form 👏 
You've done well implementing it, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 21:55 UTC, zieeco commented on index.html
> +      <form action="/my-form-page" method="post">
**[REQUIRED CHANGES]**

- Please, kindly ensure you've used the right [formspree](https://formspree.io/html) to enable the submission of a form on your portfolio website, right now, your form is not submitting as expected.

2022-06-08 21:55 UTC, zieeco commented on index.html
> +              <button class="but" type="submit">Get in Touch</button>
**[REQUIRED CHANGED]**


- Kindly add the interactions on **ALL** your buttons to indicate the hover, active, enabled, and disabled state to improve the  user experience and to meet the project requirement below:


![buton](https://user-images.githubusercontent.com/59397159/172722065-1a2f00fe-0099-4898-a4dd-d7d57066765d.png)

2022-06-08 21:55 UTC, zieeco commented on index.html
> +              <span>Get my Resume</span>
**[REQUIRED CHANGES]**

- Please, kindly improve your styling on all the `get my resume` buttons to match the Figma design below:



**figma**
![gmr](https://user-images.githubusercontent.com/59397159/172723241-94918fdf-be58-437c-8819-8cb319e941d0.png)





**your button**
![bone](https://user-images.githubusercontent.com/59397159/172722717-4916b239-ccb2-4fc5-a795-8245e272ce1a.png)

2022-06-08 21:55 UTC, zieeco commented on index.html
> +              <span>See Project</span>
**[REQUIRED CHANGES]**

- Please, kindly improve your styling on **ALL** the `see project` buttons to match the Figma design below:


**figma**
![sp](https://user-images.githubusercontent.com/59397159/172722712-c7d67a45-c97f-4998-b456-941cce4bd49b.png)


**your button**
![btwo](https://user-images.githubusercontent.com/59397159/172722794-76d0c879-c490-430a-9480-5d5533929d32.png)

2022-06-09 17:40 UTC, vechicin requested changes
# Hi @sharon-odhiambo ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing the previous reviewer's requirements.

 ## Required Changes ♻️

- [ ] Your contact section doesn't quite look like the template design.

<img width="186" alt="Screen Shot 2022-06-09 at 12 37 07" src="https://user-images.githubusercontent.com/82426682/172909559-56fe9dd0-cd20-40c2-87cc-5504e515fa03.png">

Please fix it.

_Check the comments under the review._

## Optional suggestions 📂 

- [ ] [OPTIONAL] Your design doesn't quite look like the template design.

<img width="170" alt="Screen Shot 2022-06-09 at 12 31 07" src="https://user-images.githubusercontent.com/82426682/172908536-1a5e156e-0341-4799-abb9-ae6342c77402.png">

<img width="185" alt="Screen Shot 2022-06-09 at 12 35 35" src="https://user-images.githubusercontent.com/82426682/172909300-bbbe0031-5618-4510-a0dc-1171cb91a0b2.png">

<img width="186" alt="Screen Shot 2022-06-09 at 12 36 30" src="https://user-images.githubusercontent.com/82426682/172909453-7453a9f5-745c-43b7-91cd-bf8f92693406.png">

Please check the Figma template and make sure you implement all the necessary changes to make it look as similar as possible. Some things to think about: margins, padding, fonts, colors, and button interaction styling, among other things.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 21:16 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @sharon-odhiambo  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 21:24 UTC, merged